### ISSUE TITLE
error link to kiss_icp

### ISSUE THREAD

**Issue by Wayne-DWA** [YibinWu/LIO-EKF#4]
Hi Yibin, thanks for the great work. 
I'm getting an error when building the project, it seems to be an error with the link to kiss_icp. I've compiled kiss_icp on my workspace. Can you help to fix it? Thanks.
`  Target "lio_ekf_node" links to target "kiss_icp::pipeline" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
`
`  Target "lio_ekf_node" links to target "kiss_icp::core" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?`

**Comment by hz658832** [comment]
Hi Wayne,
It seems to be a Cmake problem. If you are using cmake in an older version, e.g., 3.16.x, it cannot link kiss-icp successfully. A solution is downloading a higher version, maybe 3.20.0, and installing it on your OS. 
Cheers,
Haoming

**Comment by Wayne-DWA** [comment]
Hi Haoming, thanks!
