### ISSUE TITLE
Error during building the package

### ISSUE THREAD

**Issue by Muhammad0312** [YibinWu/LIO-EKF#5]
Did anyone face this issue when building the package:

`In file included from /home/muhammad/catkin_ws/src/LIO-EKF/src/lio_ekf.cpp:28:
/home/muhammad/catkin_ws/src/LIO-EKF/src/unscendent_transform.hpp: In function ‘SigmaPoints toSigmaPoints(const SE3d&, const MatrixType&)’:
/home/muhammad/catkin_ws/src/LIO-EKF/src/unscendent_transform.hpp:44:19: error: ‘Eigen::DenseBase<Eigen::Matrix<double, 6, 6, 0, 6, 6> >::ConstColwiseReturnType’ {aka ‘const class Eigen::VectorwiseOp<const Eigen::Matrix<double, 6, 6, 0, 6, 6>, 0>’} has no member named ‘begin’
   44 |       L.colwise().begin(), L.colwise().end(), std::next(sigma_points.begin()),
      |                   ^~~~~
/home/muhammad/catkin_ws/src/LIO-EKF/src/unscendent_transform.hpp:44:40: error: ‘Eigen::DenseBase<Eigen::Matrix<double, 6, 6, 0, 6, 6> >::ConstColwiseReturnType’ {aka ‘const class Eigen::VectorwiseOp<const Eigen::Matrix<double, 6, 6, 0, 6, 6>, 0>’} has no member named ‘end’
   44 |       L.colwise().begin(), L.colwise().end(), std::next(sigma_points.begin())`

**Comment by YibinWu** [comment]
hi, have you checked your Eigen version?

**Comment by Muhammad0312** [comment]
I have 3.3

**Comment by YibinWu** [comment]
Can you try 3.3.7?

**Comment by Muhammad0312** [comment]
it is already 3.3.7-2

**Comment by Muhammad0312** [comment]
Could the transforms be replaced with a loop as follows:
`for (int i = 0; i < dim; ++i) {
    Eigen::Matrix<double, dim, 1> col = L.col(i);
    sigma_points[i + 1] = Sophus::SE3d::exp(col) * mean;
    sigma_points[i + 1 + dim] = Sophus::SE3d::exp(-col) * mean;
  }`

**Comment by LinusNEP** [comment]
Same error here

**Comment by Muhammad0312** [comment]
Iterators were introduced in eigen 3.4 so upgrading to it works.
